[package]
name = "illus1"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.218", features = ["derive"] }
